[tool.poetry]
name = "Personal Website"
version = "0.1.0"
description = "A personal website project"
authors = ["Alex Grant <agrant@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Delacoal/website_py"
repository = "https://github.com/Delacoal/website_py"
keywords = ["website"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
website_py = "website_py.console:main"